# Generated by Django 5.2.9 on 2025-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина (м)')),
                ('crew', models.IntegerField(verbose_name='Экипаж')),
                ('passengers', models.IntegerField(verbose_name='Пассажиры')),
                ('starship_class', models.CharField(max_length=100, verbose_name='Класс корабля')),
            ],
            options={
                'verbose_name': 'Космический корабль',
                'verbose_name_plural': 'Космические корабли',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('height', models.IntegerField(verbose_name='Рост (см)')),
                ('mass', models.IntegerField(verbose_name='Вес (кг)')),
                ('hair_color', models.CharField(max_length=50, verbose_name='Цвет волос')),
                ('skin_color', models.CharField(max_length=50, verbose_name='Цвет кожи')),
                ('eye_color', models.CharField(max_length=50, verbose_name='Цвет глаз')),
                ('birth_year', models.CharField(max_length=20, verbose_name='Год рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('n/a', 'Не указан')], max_length=10, verbose_name='Пол')),
                ('homeworld', models.CharField(max_length=100, verbose_name='Родная планета')),
                ('species', models.CharField(max_length=100, verbose_name='Вид')),
                ('starships', models.ManyToManyField(related_name='pilots', to='database.starship', verbose_name='Корабли')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
