# Generated by Django 5.2.9 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='swapi_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='starship',
            name='swapi_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
