# Generated by Django 5.2.9 on 2025-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_character_swapi_id_starship_swapi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='swapi_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID в SWAPI'),
        ),
        migrations.AlterField(
            model_name='starship',
            name='swapi_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID в SWAPI'),
        ),
    ]
